version: '3.8'
services:
  web:
    image: bucchub/php-apache:8.2
    container_name: web
    restart: always
    environment:
      TZ: 'Asia/Bangkok'
    ports:
      - '80:80'
    volumes:
      - /home/web/:/var/www/html
      - web-config:/etc/apache2
      - web-log:/var/log/apache2
      - php-config:/usr/local/etc/php
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - db-config:/etc/mysql/conf.d
    environment:
      TZ: 'Asia/Bangkok'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      TZ: 'Asia/Bangkok'
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
      UPLOAD_LIMIT: 1024M
    ports:
      - 8081:80
networks:
  default:
    name: web-net
volumes:
  web-log:
  web-config:
  php-config:
  db-data:
  db-config:
